version: '3'
services:
  etcd:
    image: bitnami/etcd:latest
    ports:
      - "2379:2379"
      - "2380:2380"
    environment:
      # - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ROOT_PASSWORD=root1234
      # - ETCD_Name=node
      # - ETCD_INITIAL_CLUSTER=node
      # - ETCD_INITIAL_CLUSTER_STATE=new
      # - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      # - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://0.0.0.0:2379
    networks:
      - etcd_network
    
networks:
  etcd_network:
    driver: bridge