// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"learn_wire/demo"
)

// Injectors from wire.go:

func InitializeZ(cxt context.Context) (demo.Z, error) {
	x := demo.NewX()
	y := demo.NewY(x)
	z, err := demo.NewZ(cxt, y)
	if err != nil {
		return demo.Z{}, err
	}
	return z, nil
}
